# ********RoostGPT********
"""
Application Test generated by RoostGPT for test ImproveTest-Check using AI Type Open AI and AI Model gpt-4-turbo


"""

# ********RoostGPT********
import pytest
from src.server.instance import server
from src.resources.book import Book, BookList

@pytest.fixture
def client():
    with server.app.test_client() as client:
        yield client

def test_get_book_list(client):
    response = client.get('/books')
    assert response.status_code == 200
    assert isinstance(response.get_json(), list)

def test_get_single_book(client):
    response = client.get('/books/0')
    assert response.status_code == 200
    data = response.get_json()
    assert data['id'] == 0 and data['title'] == 'War and Peace'

def test_book_not_found(client):
    response = client.get('/books/999')
    assert response.status_code == 404

def test_add_book(client):
    new_book = {"title": "New Book"}
    response = client.post('/books', json=new_book)
    assert response.status_code == 200
    assert 'id' in response.get_json()

def test_delete_book(client):
    response = client.delete('/books/1')
    assert response.status_code == 200

def test_update_book(client):
    book_update = {"title": "Updated Title"}
    response = client.put('/books/0', json=book_update)
    assert response.status_code == 200
    assert response.get_json()['title'] == "Updated Title"

# TODO: Define more tests considering edge cases and exceptional conditions.

